### ISSUE TITLE
Example animated gifs/videos produced by your code

### ISSUE THREAD

**Issue by jmtatsch** [alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions#1]
Can you post some animated gifs/videos produced by your code?

**Comment by alexandrosstergiou** [comment]
Sorry for the late reply. Examples have been added based on outputs of [Multi-Fibre Net](https://github.com/cypw/PyTorch-MFNet) for both action (UCF-101) and ego-centric (EPIC-Kitchens) datasets.
