### ISSUE TITLE
How to use your code

### ISSUE THREAD

**Issue by Fazlik995** [alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions#3]
Hi @alexandrosstergiou 

Thank you for sharing your awesome work.

I would like to get visualization results for my network. However, I do not understand how to run your code.

Should I integrate some part of "heat_tubes_mfnet_pytorch.py" into my network or I should adjust my pre-trained model into your code?

Please, help me to clarify how to use your code

Thank you

**Comment by alexandrosstergiou** [comment]
Hi @Fazlik995 

You can replace the import statement at [line #11](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions/blob/caa0f8a6e5609dc7404e5e76a9edc44f599a18cf/heat_tubes_mfnet_pytorch.py#L11) and the model class call at [line #60](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions/blob/caa0f8a6e5609dc7404e5e76a9edc44f599a18cf/heat_tubes_mfnet_pytorch.py#L60), if you want to use your own custom 3D-CNN. Also note that if you have not trained with `DataParallel` you should comment out [line #61](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions/blob/caa0f8a6e5609dc7404e5e76a9edc44f599a18cf/heat_tubes_mfnet_pytorch.py#L61). The parser arguments can be used as normal, i.e. :

- `num_classes`: The number of output units/dataset classes used in the network.
- `model_weights`: Directory of the model weights.
- `frame_dir`: Directory for all the image frames that you want to visualise. - If they are more than 16 you can [adapt the `load_images` function](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions/blob/caa0f8a6e5609dc7404e5e76a9edc44f599a18cf/heat_tubes_mfnet_pytorch.py#L22) to hold larger/smaller number of frames and [change the `frame_indices` variable](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions/blob/caa0f8a6e5609dc7404e5e76a9edc44f599a18cf/heat_tubes_mfnet_pytorch.py#L54)
- `label`: integer for the class to visualise (should have a direct correspondence to a neurone in the output layer).
- `--base_output_dir`: String for where to save the output visualisations

So the call to the script is something like:
```
$ python heat_tubes_mfnet_pytorch.py num_classes 100 model_weights /my/path/to/the/weights.pth frame_dir some/frames label 45 
```


In addition, you can changes the colours of the opencv `ColorMap` [here](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions/blob/caa0f8a6e5609dc7404e5e76a9edc44f599a18cf/heat_tubes_mfnet_pytorch.py#L102)
